//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class AddData
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter your name", AllowEmptyStrings = false)]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter your Number", AllowEmptyStrings = false)]
        public string Number { get; set; }
        [Required(ErrorMessage = "Please enter your email address", AllowEmptyStrings = false)]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter your Message in few words", AllowEmptyStrings = false)]
        public string Message { get; set; }
       
    }
}
