//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Number { get; set; }
        public string Location { get; set; }
        public string email { get; set; }
        public string message { get; set; }
    }
}
